group {
    col.border_active = $activeWindowBorderColour
    col.border_inactive = $inactiveWindowBorderColour
    col.border_locked_active = $activeWindowBorderColour
    col.border_locked_inactive = $inactiveWindowBorderColour

    groupbar {
        font_family = JetBrains Mono NF
        font_size = 15
        gradients = true
        gradient_round_only_edges = false
        gradient_rounding = 5
        height = 25
        indicator_height = 0
        gaps_in = 3
        gaps_out = 3

        text_color = rgb($onPrimary)
        col.active = rgba(c2c1ffd4)
        col.inactive = rgba(918f9ad4)
        col.locked_active = rgba(c2c1ffd4)
        col.locked_inactive = rgba(c6c4e0d4)
    }
}
