plugin {
    hyprbars {
        bar_height = 24
        bar_color = rgba(13131755)
        bar_blur = true
        col.text = rgba(e5e1e7FF)
        bar_text_size = 11
        bar_text_font = JetBrainsMonoNL Nerd Font
        bar_text_align = center
        bar_buttons_alignment = right
        bar_padding = 7
        bar_button_padding = 5
        bar_part_of_window = true
        bar_precedence_over_border = true
        icon_on_hover = true
        inactive_button_color = rgba(47464f99)
        on_double_click = hyprctl dispatch fullscreen 1

        hyprbars-button = rgb(ff4040), 12, , hyprctl dispatch killactive, rgb(ffffff)
        hyprbars-button = rgb(0bb30b), 12, , hyprctl dispatch fullscreen 1, rgb(ffffff)
        hyprbars-button = rgb(409cff), 12, , hyprctl dispatch movetoworkspacesilent special:minimized, rgb(ffffff)
    }
}
